apiVersion: v1
kind: Service
metadata:
  name: startup-nextjs-service
spec:
  selector:
    app: startup-nextjs-fabian
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
