apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: startup-nextjs-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: startup-nextjs-fabian
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
