apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: startup-nextjs-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-web-app-deployment
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
