apiVersion: apps/v1
kind: Deployment
metadata:
  name: startup-nextjs-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: startup-nextjs-fabian
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: startup-nextjs-fabian
    spec:
      containers:
        - name: startup-nextjs-fabian
          image: fabiannaether/startup-nextjs-fabian:latest
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
